application: tasklist-997
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /images
  static_dir: images 

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


- url: /.*
  script: taskList.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest